[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

upload_protocol = esptool

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit SHT31 Library
    adafruit/Adafruit ADS1X15
    mikalhart/TinyGPSPlus
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32
    knolleary/PubSubClient


[env:esp32-s3-ota]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

upload_protocol = espota
upload_port = 10.168.243.80

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit SHT31 Library
    adafruit/Adafruit ADS1X15
    mikalhart/TinyGPSPlus
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32
    knolleary/PubSubClient